version: '3'
services:

  notebook:
    
    build:
      context: . 
      dockerfile: Dockerfile
    
    ports:
      - ${APP_PORT}:${APP_PORT}
    
    restart: unless-stopped

    volumes:
      - ./src:/workspace/src

    environment:
      - APP_PORT=${APP_PORT}